<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Copy From Facebook</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>30d69421-b0ec-4400-87dd-c67d37e1eff4</testSuiteGuid>
   <testCaseLink>
      <guid>233b2979-793d-4e13-b855-afcee8c94be8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Text</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2fb4da-0315-40d0-9bdf-50b3594066ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11bdb6d7-64cd-435b-964a-0eebc6b73aa0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c7da2bd9-4f88-4d95-8681-f2d744579f3a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook button</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb3acdf4-9530-4b39-b0f9-20c7b2b0ee0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cd55e70-4ab9-4de0-b665-1a61b9acecf0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1aa1b499-0146-445d-839d-00e0ad801415</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>419fa01a-4639-4f00-9cdf-03eeee58016c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e15f75d4-2ba1-4c1a-a6ee-c714391961b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>37409081-f5b6-41bb-a40c-e600f8b8dbb2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook video</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e4ce2dc-e647-415a-8145-429b856689c2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae734117-74c7-4baf-8e46-562a885d7c88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>06ea914f-4fe8-4531-a893-3c51dcb5c4b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Carousel</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ced9760-cb11-432e-a6c7-f965481da7f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0750301e-cd7a-42b4-bce3-39881106d1bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8909344-7610-4131-83db-44b9e28d18ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Form Builder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32174ba0-37c2-41df-a4dd-4d90ae7268bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fb2ca5a-fa76-493a-9194-87e2c5e02677</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1dcb0ee8-c654-4a93-be4a-e6e9d67e3750</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Subscription</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3f2f78fd-9c11-4416-ae14-2e6f92e9eae2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2eb6e314-c3d0-4b47-82f7-d8d60cb07a41</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aaf77bc7-8f22-4569-8203-fbd995bd41ab</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Countinue to block</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe04ee33-4183-4c96-b6b2-6860c3057662</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>163a76df-df3a-4488-9fef-5c1fa5c08832</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>396021c4-c4e0-4010-b095-4f9e6e53739b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Live Chat</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92cd43c2-c1ed-40d4-94ab-37b4d743cf27</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>298e0564-8af2-4047-82cc-4e7035fc4bf2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e668a2f9-fed9-44f7-a74d-30c000f831c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Customer Attribute</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b06bb45-b6bf-4dae-88a0-58a1eb5298ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1641e998-879c-462e-95c4-f46c3a88a851</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>260a6e1c-9d0f-463f-8b41-c5e6d0da4d08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Subscribe to sequence</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cae19e3-5a7e-42db-9f06-61ca6e290cb6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29f26542-0f3c-4d32-8316-ca57aee6d654</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a51aed36-d30c-4363-ae9e-dd9e7ed61432</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Unsubscribe to sequence</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>761637dd-2101-46c8-a826-534ff5904160</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5bf1e051-491c-4681-a3d1-25b61c3d432b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0e26b1bd-d4e2-4bae-ab26-6ca250f71777</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Customer Suspension</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f4d71be-1aef-4a08-bd97-19f98b7c9c2d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfe6b5eb-e46b-4b06-840f-1ac63eb60b96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>db5a4f80-696b-44e4-a7dd-54d1bac0f676</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Customer Tag</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa5389d2-0622-493d-b9a5-06be1d9667e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d42fbd7b-7efc-4bf2-9c7a-51d941061279</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb194efb-0e03-4f6d-9d33-a43dbe35820b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Product</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d87f81c2-eafc-4473-b665-58f6ef007d84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6da8531-5a7b-4a2b-b107-2a05172ada6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e022a49-78cd-45ec-b808-8a85fa183938</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Product Responder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>74475e43-a5b1-4774-a7da-81f573776be9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55d2a427-e749-47b5-b56c-63a3bb11d2a6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ab127a3-7c75-4235-88a0-e36569a01c1d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook FB APP Event</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d788a8e-bf79-4dbe-b87e-77a4b9be325e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae317ff8-b03a-4ed4-a02a-13e6a124ceda</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9233c623-ba4b-4206-9052-aded72796613</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook API</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28abcb11-fedd-48f4-9437-fb12bf2c4f9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdd17842-8bb7-4439-9936-a16ebca95e68</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>94a52f3b-8682-4a48-82ee-96c26c229fc8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Media Template</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1524f837-f17a-4696-ace2-9af8f7955bc2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>609d86c5-04f5-4bb0-82cb-84ca2757b7dd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfa1d7b2-f298-46fa-a407-d12e01b097e5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Store Locator</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a15a481-4672-4dd4-b0f2-2b3b314bcd7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e7b314b-493c-40b3-bb8e-71e4ab6357de</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>643f4e73-9d28-45aa-a04e-b7d122939f8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Quick Reply</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>760291bc-66bb-4fad-94a6-e00f67511b57</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dec2674b-8cca-4051-91de-0fe3a14b0760</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>38473c39-4575-423f-9ef5-8d1b51a99135</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Send Email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05dfe8e2-cdae-4d55-a6f7-e61a25a96c01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>26ce6144-8e65-4aa4-9a34-f46f2a3ea59c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2619ce4-58e0-4718-b5e3-c92c2253a315</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Promotion Listing</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdb5e8cc-5c5b-4227-9963-84b8acacebbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a78bdf2-a9e8-483f-86bf-c4a377581225</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81cf097a-9fce-4728-937f-48084f9eff43</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook Customer Attribute Snapshot</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>938e52c5-1760-4a27-8ff1-c2f120ad1a7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11260b4a-8490-4c96-9ab4-2bb859fed33f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e2ff56ef-82ff-4b83-a2cf-b931a5328981</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Copy from Facebook/Facebook API template</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d2d13ba-6d67-4a15-835c-45ed2bac1def</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>034b0731-ad8a-44f2-8449-22b52a71a032</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
