<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Instagram Direct Create</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d5f4e088-487f-4ff3-8619-e83a6c9aa4e6</testSuiteGuid>
   <testCaseLink>
      <guid>bb28d25e-f984-49dd-a861-0d700f16e22b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Text</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12a7b2c2-cc00-4c9d-8c62-f090416af89b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e06752e-c257-4b21-bb13-5e74b7ebbe2f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5edd6000-855c-4db7-8db8-c23c2ddd27c0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Image</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee681ada-baa3-4986-be2a-4449e8ebc86f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>387e2774-bb14-4e1f-a271-b76b30098ecc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a75c2136-db9a-4474-9a35-7dd8482ad417</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Form Builder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d2d02ec-a951-4c33-84c6-6717804b608f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1e7d392-4ce4-482e-8df5-1731648c2514</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7ba1a1b-e796-41bb-9767-2f73f45848b9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Subscription</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5fd8c8c3-0eb0-4450-ad3e-ecc110909432</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d085a51d-6fc8-44af-bb1f-d34ac176d037</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f7dd127-c5c3-40e8-b8ae-493a009efe92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Countinue to block</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50d7996a-0d69-43dc-b073-cff91601c160</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db4f9ee5-5ce4-45da-b9a8-cd9a57a283e0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c5e5667e-3111-46e3-bbaa-b6b3f55c8c32</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Live Chat</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>207cc7e3-dd66-4f42-bf01-05458d9e78d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40be0af9-d806-4341-b417-f03c1789f646</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cc178c79-cda1-49ac-9684-3ecf81757ddf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Customer Attribute</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>831d3b16-a8a7-4f38-b049-f0be076b8e29</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a08d241-9650-454b-aed9-9bb42cfc31e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1661e1b2-749b-4077-a793-c5b201322cd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Subscribe to sequence</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b210d70-6901-465c-9945-a15a48555d4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68fa557c-e516-4ab7-919a-08dbc9c3ba20</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bce5cd7-96ed-45fb-a907-0b300ace7c55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Unsubscribe to sequence</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae1acb27-c2e1-4034-be7d-ac361193e54d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3142cfb2-7fcd-4c52-91c5-f9b129747375</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0139f640-ea52-4209-8d67-66cb11a3c9fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Customer Suspension</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f3d5fdf-120c-4ae6-98c3-1d1d90bc76fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9baaa88c-49ac-456e-8a9c-1f4e7f65bb51</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae80668e-6c3f-4989-87a6-3a7d5fcb069f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Customer Tag</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>682ce4c0-69c5-42cb-aec2-59fd9e9db0bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ebe485b5-20a8-4bb4-b3a5-37b42b73732a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a1fa62b-571a-4136-8834-139572f79648</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram API</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5865adab-510e-4bf5-a1bf-6bc005c0d45c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e49ce19-ae0f-4ef4-9a6d-9e78d46f0a88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60291de8-3b44-420a-bb62-e855031a8f1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Quick Reply</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8acca2c-2fb7-4c82-aa13-027d836e25dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e0c6489-8b08-4ca4-9743-9547bdc812a8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>804db2f3-31a2-4ca5-a394-2971efe418cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Send Email</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6f4d5c4-a7d2-4171-b087-7e427f952e02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51e2afdb-ada1-46d6-9280-aeec845d5e63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5e8a525-48cf-4763-9d0d-098f477a7e5d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CMS/Instagram Create Content Card/Instagram Customer Attribute Snapshot</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c8ce83f-06ed-4833-877b-b872cd6d29e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b27714f3-7699-44b4-9505-9481ff7058b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
