<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scrollTo</name>
   <tag></tag>
   <elementGuidId>c1e4330b-bb0a-458d-bcf4-8e879d3e5465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//b[contains(.,'Type')])[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
